layout: 
fname: 
lname: 
email:
dline: 
cline: 
department: 
company: 
title: 
extra: 
picture: 
vcard: 
bio_url: 
wpcf_profile_linkedin: 
gender: 
broker: 

include: ["_people"]
permalink: "/:title.htm"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

ignore: ".py"