layout:
fname:
lname:
des: 
sig_logo: 
license: 
email:
direct_line:
cell_line: 
department:
company:
title:
extra_link: 
extra_content: 
vcard:

include: ["_people"]
permalink: "/:title.htm"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

ignore: ".py"